 # https://taskfile.dev

version: "3"

vars:
  DOCKER_TAG: 0.0.1
  DOCKER_IMAGE: "docker.io/fl64/vm-diy:{{ .DOCKER_TAG }}"
  NAMESPACE: diy


tasks:

  ssh-gen:
    cmds:
      - yes | ssh-keygen -t ed25519 -b 1024 -f ./test/diy -N "" -C "diy" -v
      - chmod 400 ./test/diy


  docker-build:
    cmds:
      - docker build -t {{ .DOCKER_IMAGE }} -f ./image/Dockerfile .

  docker-push:
    deps:
      - docker-build
    cmds:
      - docker push {{ .DOCKER_IMAGE }}


  deploy:
    cmds:
    - kubectl apply -k ./manifests

  undeploy:
    cmds:
    - kubectl delete -k ./manifests

  con:
    cmds:
    - kubectl -n diy exec -it deploy/vm -- virsh console vm

  exec:
    cmds:
    - kubectl -n diy exec -it deploy/vm -- bash

  port-forward:
    cmds:
    - kubectl -n diy port-forward deploy/vm 2222:2222

  ssh:
    cmds:
    - ssh -p 2222 -i ./test/diy -o StrictHostKeyChecking=no cloud@localhost

  get-node-port:
    cmds:
    -  kubectl -n diy get svc ssh -o json | jq '.spec.ports[] | select(.port==2222) | .nodePort'
