#cloud-config
users:
  - name: cloud
    passwd: $6$7aSB2MyvJn6FcDM8$vYdRNmurQ0XJ22i9v.boMjZYfEdBNqScIXV2PB4zIm4LfddBHarFdJtceVy6AXLWnkq87UULH9VW4aEcRW3LX/
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG7g3PDeyatIvZRTMs1M243QnzkJwVzugBDNkaZjqiLM diy
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - systemctl enable --now qemu-guest-agent.service
final_message: "🔥🔥🔥 The system is finally up, after $UPTIME seconds 🔥🔥🔥"
