---
apiVersion: v1
kind: Pod
metadata:
  name: vm
  namespace: diy
spec:
  containers:
    - image: docker.io/fl64/vm-diy:0.0.1
      imagePullPolicy: Always
      command: ["/entrypoint.sh"]
      name: compute
      resources:
        requests:
          cpu: "500m"
          memory: "3Gi"
        limits:
          cpu: "500m"
          memory: "3Gi"
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /disks/
          name: disk
        - name: cloud-init
          mountPath: /config
        - name: entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
  volumes:
    - name: disk
      persistentVolumeClaim:
        claimName: disk
    - name: kvm
      hostPath:
        path: /dev/kvm
        type: ""
    - name: cloud-init
      configMap:
        name: cloud-init
    - name: entrypoint
      configMap:
        name: entrypoint
        defaultMode: 0777
