---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk
  namespace: diy
spec:
  storageClassName: nfs-pod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
