apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  type: NodePort
  #externalTrafficPolicy: Cluster
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
  selector:
    app: vm
